In [11]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf
from sklearn.utils import resample

In [36]:
file = 'Resampling/FCV_Oversampled.csv'
df = pd.read_csv(file)

df.head()

,Previous PHEVs,Previous BEVs,Previous HEVs,Previous CNGs,Household Income,"Importance of reducing greenhouse gas emissions (-3 not important, 3 important)",Home ownership (own 1),Home Type (detached 1),Highest Level of Education,Longest trip in the last 12 months,...,One-way commute distance,Number of people in the household,Age,Gender (Male 1),Number of vehicles in the household,Annual VMT Estimate,Model Year,Manufacture_encoded,Model_encoded,Target
0,1.0,0.0,0.0,0.0,275000.0,2.52,1.0,1.0,3.0,483.14,...,0.01,2.0,65.0,0.0,2,14622.000000,2016,12,4,0.0
1,0.0,0.0,1.0,0.0,275000.0,2.76,1.0,1.0,4.0,568.09,...,10.69,3.0,65.0,0.0,3,9197.142857,2016,12,4,0.0
2,1.0,0.0,0.0,0.0,125000.0,2.60,1.0,1.0,2.0,255.16,...,17.63,2.0,55.0,0.0,3,5082.352941,2017,12,4,0.0
3,0.0,0.0,1.0,0.0,175000.0,1.23,1.0,1.0,4.0,312.78,...,3.53,2.0,75.0,0.0,2,13025.454545,2016,12,4,0.0
4,0.0,0.0,1.0,0.0,500000.0,1.08,1.0,1.0,2.0,125.79,...,28.05,3.0,45.0,0.0,3,18000.000000,2016,12,4,0.0

In [37]:
ml_df = df.copy()

In [38]:
ml_df = ml_df.rename(columns={'FCV, BEV Dummy' : 'Target'})

In [39]:
X = ml_df.drop(columns=('Target'), axis = 1)
y = ml_df['Target']

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [41]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [42]:
# Create the SVM model
svm = SVC(kernel='linear')

In [ ]:
# Train the model
svm.fit(X_train, y_train)

In [34]:
y_pred = svm.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_pred,
   "Actual": y_test
}).reset_index(drop=True)
results

      Prediction  Actual
0            0.0     1.0
1            0.0     0.0
2            0.0     1.0
3            0.0     1.0
4            0.0     0.0
...          ...     ...
2230         0.0     0.0
2231         0.0     1.0
2232         1.0     1.0
2233         0.0     0.0
2234         0.0     1.0

[2235 rows x 2 columns]

In [35]:
# Evaluate the model
accuracy_score(y_test, y_pred)

0.6366890380313199